CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imported_at TEXT NOT NULL,
    source_file TEXT NOT NULL,
    date_time TEXT,
    date TEXT,
    type TEXT,
    order_id TEXT,
    sku TEXT,
    description TEXT,
    quantity DOUBLE PRECISION,
    product_sales DOUBLE PRECISION,
    product_sales_tax DOUBLE PRECISION,
    shipping_credits DOUBLE PRECISION,
    shipping_credits_tax DOUBLE PRECISION,
    gift_wrap_credits DOUBLE PRECISION,
    giftwrap_credits_tax DOUBLE PRECISION,
    regulatory_fee DOUBLE PRECISION,
    tax_on_regulatory_fee DOUBLE PRECISION,
    promotional_rebates DOUBLE PRECISION,
    promotional_rebates_tax DOUBLE PRECISION,
    marketplace_withheld_tax DOUBLE PRECISION,
    selling_fees DOUBLE PRECISION,
    fba_fees DOUBLE PRECISION,
    other_transaction_fees DOUBLE PRECISION,
    other DOUBLE PRECISION,
    total DOUBLE PRECISION,
    transaction_status TEXT,
    sales_o_to_y DOUBLE PRECISION,
    order_state TEXT,
    order_city TEXT,
    order_postal TEXT,
    tx_key TEXT,
    channel TEXT DEFAULT 'Amazon'
);

CREATE TABLE IF NOT EXISTS sku_mapping (
    sku_key TEXT PRIMARY KEY,
    sku TEXT,
    asin TEXT,
    parent_asin TEXT,
    brand TEXT,
    tag TEXT,
    product_line TEXT,
    updated_at TEXT,
    unit_count TEXT,
    flavor_name TEXT,
    size TEXT,
    cogs DOUBLE PRECISION,
    price DOUBLE PRECISION,
    promo DOUBLE PRECISION,
    link_to_pdp TEXT
);

CREATE TABLE IF NOT EXISTS imports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imported_at TEXT NOT NULL,
    source_file TEXT NOT NULL,
    row_count BIGINT NOT NULL,
    min_date TEXT,
    max_date TEXT,
    total_sales_o_to_y DOUBLE PRECISION NOT NULL,
    channel TEXT DEFAULT 'Amazon'
);

CREATE TABLE IF NOT EXISTS monthly_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    channel TEXT NOT NULL,
    product_line TEXT NOT NULL,
    goal DOUBLE PRECISION NOT NULL,
    source_file TEXT,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS asin_cogs (
    asin_key TEXT PRIMARY KEY,
    asin TEXT,
    sku TEXT,
    cogs DOUBLE PRECISION NOT NULL,
    source_sheet TEXT,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS state_updates (
    date_time TEXT,
    type TEXT,
    order_id TEXT,
    sku TEXT,
    total DOUBLE PRECISION,
    order_state TEXT,
    source_file TEXT
);

CREATE TABLE IF NOT EXISTS _state_updates_small (
    date_time TEXT,
    type TEXT,
    order_id TEXT,
    sku TEXT,
    total DOUBLE PRECISION,
    order_state TEXT
);

CREATE TABLE IF NOT EXISTS _location_backfill_updates_small (
    date_time TEXT,
    type TEXT,
    order_id TEXT,
    sku TEXT,
    total DOUBLE PRECISION,
    order_state TEXT,
    order_city TEXT,
    order_postal TEXT
);

CREATE TABLE IF NOT EXISTS _location_backfill_updates_hist (
    date_time TEXT,
    type TEXT,
    order_id TEXT,
    sku TEXT,
    total DOUBLE PRECISION,
    order_state TEXT,
    order_city TEXT,
    order_postal TEXT
);

CREATE TABLE IF NOT EXISTS slack_daily_alerts (
    alert_date TEXT PRIMARY KEY,
    sent_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imported_at TEXT NOT NULL,
    source_file TEXT NOT NULL,
    row_count BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id BIGINT NOT NULL REFERENCES inventory_snapshots(id),
    imported_at TEXT NOT NULL,
    source_file TEXT NOT NULL,
    sku TEXT,
    fnsku TEXT,
    asin TEXT,
    product_name TEXT,
    condition TEXT,
    your_price DOUBLE PRECISION,
    afn_warehouse_quantity DOUBLE PRECISION,
    afn_fulfillable_quantity DOUBLE PRECISION,
    afn_unsellable_quantity DOUBLE PRECISION,
    afn_reserved_quantity DOUBLE PRECISION,
    afn_total_quantity DOUBLE PRECISION,
    afn_inbound_working_quantity DOUBLE PRECISION,
    afn_inbound_shipped_quantity DOUBLE PRECISION,
    afn_inbound_receiving_quantity DOUBLE PRECISION,
    afn_researching_quantity DOUBLE PRECISION,
    product_line TEXT
);

CREATE TABLE IF NOT EXISTS app_settings (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ntb_imports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imported_at TEXT NOT NULL,
    source_file TEXT NOT NULL,
    row_count BIGINT NOT NULL,
    min_month TEXT,
    max_month TEXT,
    channel TEXT DEFAULT 'Amazon'
);

CREATE TABLE IF NOT EXISTS ntb_monthly (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id BIGINT NOT NULL REFERENCES ntb_imports(id),
    month TEXT NOT NULL,
    product_line TEXT NOT NULL,
    ntb_customers DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS shopify_imports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imported_at TEXT NOT NULL,
    source_file TEXT NOT NULL,
    product_line TEXT NOT NULL,
    row_count BIGINT NOT NULL,
    min_date TEXT,
    max_date TEXT
);

CREATE TABLE IF NOT EXISTS shopify_line_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id BIGINT NOT NULL REFERENCES shopify_imports(id),
    date TEXT NOT NULL,
    product_line TEXT NOT NULL,
    sales DOUBLE PRECISION NOT NULL,
    units DOUBLE PRECISION NOT NULL DEFAULT 0,
    orders DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_transactions_tx_key ON transactions(tx_key);
CREATE INDEX IF NOT EXISTS idx_transactions_channel_date ON transactions(channel, date);
CREATE INDEX IF NOT EXISTS idx_imports_channel_imported_at ON imports(channel, imported_at);
CREATE INDEX IF NOT EXISTS idx_ntb_imports_channel_imported_at ON ntb_imports(channel, imported_at);
CREATE INDEX IF NOT EXISTS idx_ntb_monthly_import ON ntb_monthly(import_id);
CREATE INDEX IF NOT EXISTS idx_ntb_monthly_month ON ntb_monthly(month);
CREATE INDEX IF NOT EXISTS idx_shopify_line_daily_date ON shopify_line_daily(date);
CREATE INDEX IF NOT EXISTS idx_shopify_line_daily_line_date ON shopify_line_daily(product_line, date);
CREATE INDEX IF NOT EXISTS idx_location_backfill_small_key ON _location_backfill_updates_small(date_time, type, order_id, sku, total);
CREATE INDEX IF NOT EXISTS idx_location_backfill_hist_key ON _location_backfill_updates_hist(date_time, type, order_id, sku, total);
CREATE UNIQUE INDEX IF NOT EXISTS idx_monthly_goals_unique ON monthly_goals(year, month, channel, product_line);
